// <auto-generated />
namespace ContactManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ContactManagerModelsTask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContactManagerModelsTask));
        
        string IMigrationMetadata.Id
        {
            get { return "201408151032520_ContactManager.Models.Task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
